name: distance_measurement_app
description: distance measuring app (range finder)
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  network_info_plus: ^4.0.1
  permission_handler: ^11.0.0
  provider: ^6.0.5
  flutter_zoom_drawer: ^3.1.1
  package_info_plus: ^4.0.2
  auto_route: ^7.7.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.0
  intl: ^0.18.0  
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.2.0
  golden_toolkit: ^0.15.0
  
  
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21 #
  adaptive_icon_background: "#808080"
  adaptive_icon_foreground: "assets/icon.jpg" # only available for Android 8.0 devices and above

flutter:  
  uses-material-design: true
  generate: true
  assets:
    - assets/menu_background.jpg
    - assets/distance_background.jpg
    - assets/icon.jpg
  fonts:
    - family: RaleWay
      fonts:
        - asset: assets/fonts/rale_way/static/RaleWay-Regular.ttf
        - asset: assets/fonts/rale_way/static/RaleWay-Italic.ttf
  